apiVersion: apps/v1
kind: Deployment
metadata:
  name: yourls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yourls
  template:
    metadata:
      labels:
        app: yourls
    spec:
      containers:
        - name: yourls
          image: yourls:latest
          ports:
            - containerPort: 8080
          env:
            - name: YOURLS_DB_HOST
              value: mysql-service
            - name: YOURLS_DB_NAME
              value: "bowie-db"
            - name: YOURLS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
            - name: YOURLS_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: YOURLS_DB_PREFIX
              value: bowie_
            - name: YOURLS_SITE
              valueFrom:
                configMapKeyRef:
                  name: yourls-config
                  key: YOURLS_SITE
            - name: YOURLS_USER
              valueFrom:
                configMapKeyRef:
                  name: yourls-config
                  key: YOURLS_USER
            - name: YOURLS_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password

---

#external service to access mongo-express UI
apiVersion: v1
kind: Service
metadata:
  name: yourls-service
spec:
  selector:
    app: yourls
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008